### ISSUE TITLE
Bot token issue

### ISSUE THREAD

**Issue by Iyxan23** [AdityaGupta345/NimbuBot#1]
https://github.com/AdityaGupta345/NimbuBot/blob/56e6851c5dca4d8f5147e8b2d2d16d8029500168/main.py#L38

Uhm, you shouln't just put your bot's token publicly on github, people can use it to steal and impersonate your bot. You should put it on your system's environment variables instead.

Removing this manually on github wouldn't really help, as every commits are recorded, people can just go back in time to get the token. To "squash" the commit history, you may want to check out [rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing)

**Comment by AdityaGupta345** [comment]
mmm bro i revoke The bot token everyday . so now this token wont work as it is expired😂

**Comment by Iyxan23** [comment]
haha nice
